sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: NGINX_VERSION=1.12.2 BROTLI_VERSION=bfd2885
    - env: NGINX_VERSION=1.13.9 BROTLI_VERSION=bfd2885

script:
    - travis_wait python travis.py